### ISSUE TITLE
Invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by mappum** [facebookresearch/deepcluster#26]
The training script is failing after completing an epoch:
```
$ python main.py --verbose --k 1000 ./images
Architecture: alexnet
Load dataset: 0.35 s
Compute features
main.py:296: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = torch.autograd.Variable(input_tensor.cuda(), volatile=True)
0 / 215	Time: 7.964 (7.964)
200 / 215	Time: 0.067 (1.363)
k-means loss evolution: [74579.91  44611.473 43375.715 42842.293 42551.477 42388.676 42286.797
 42216.695 42169.83  42135.938 42109.06  42090.5   42076.816 42066.973
 42059.99  42054.387 42049.074 42045.258 42041.926 42039.15 ]
k-means time: 8 s
Save checkpoint at: checkpoints/checkpoint_0.pth.tar
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 181, in main
    loss = train(train_dataloader, model, criterion, optimizer, epoch)
  File "main.py", line 265, in train
    losses.update(loss.data[0], input_tensor.size(0))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```

It can successfully start from the checkpoint, but still fails after the next epoch.

**Comment by mappum** [comment]
My mistake, it's not actually completing an epoch.

**Comment by mappum** [comment]
Changing `loss.data[0]` to `loss.item()` in line 265 as recommended by the error message fixed the issue for me. I don't know enough about Torch to know why it was different for me, should this be fixed in a PR?

**Comment by mathildecaron31** [comment]
Hi, this is due to a mismatch pytorch version. This code is written for pytorch 0.2.

**Comment by fpczk** [comment]
Maybe this should be added to the readme, since most of the users trying out this project by now should experience this problem. (Because by default, a newer version of pytorch will most probably get installed)
