### ISSUE TITLE
Error loading PyTorch vgg16 model

### ISSUE THREAD

**Issue by JonMuehlst** [facebookresearch/deepcluster#34]
When loading the downloaded vgg16 model with the following code:

`import torch`
`from models import vgg16`

`model = vgg16(sobel=True, bn=True, out=10000)`

`PATH = '/path/to/deepcluster_models/vgg16/checkpoint.pth.tar'`
`checkpoint = torch.load(PATH)`
`model.load_state_dict(checkpoint['state_dict'])`

I receive the following error:

`Traceback (most recent call last):
  File "<input>", line 10, in <module>
  File "/path/to/lib/python3.5/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
	Missing key(s) in state_dict: "features.0.weight", "features.0.bias", "features.1.weight", "features.1.bias", "features.1.running_var", "features.1.running_mean", "features.3.weight", "features.3.bias", "features.4.weight", "features.4.bias", "features.4.running_var", "features.4.running_mean", "features.7.weight", "features.7.bias", "features.8.weight", "features.8.bias", "features.8.running_var", "features.8.running_mean", "features.10.weight", "features.10.bias", "features.11.weight", "features.11.bias", "features.11.running_var", "features.11.running_mean", "features.14.weight", "features.14.bias", "features.15.weight", "features.15.bias", "features.15.running_var", "features.15.running_mean", "features.17.weight", "features.17.bias", "features.18.weight", "features.18.bias", "features.18.running_var", "features.18.running_mean", "features.20.weight", "features.20.bias", "features.21.weight", "features.21.bias", "features.21.running_var", "features.21.running_mean", "features.24.weight", "features.24.bias", "features.25.weight", "features.25.bias", "features.25.running_var", "features.25.running_mean", "features.27.weight", "features.27.bias", "features.28.weight", "features.28.bias", "features.28.running_var", "features.28.running_mean", "features.30.weight", "features.30.bias", "features.31.weight", "features.31.bias", "features.31.running_var", "features.31.running_mean", "features.34.weight", "features.34.bias", "features.35.weight", "features.35.bias", "features.35.running_var", "features.35.running_mean", "features.37.weight", "features.37.bias", "features.38.weight", "features.38.bias", "features.38.running_var", "features.38.running_mean", "features.40.weight", "features.40.bias", "features.41.weight", "features.41.bias", "features.41.running_var", "features.41.running_mean". 
	Unexpected key(s) in state_dict: "features.module.0.weight", "features.module.0.bias", "features.module.1.weight", "features.module.1.bias", "features.module.1.running_mean", "features.module.1.running_var", "features.module.3.weight", "features.module.3.bias", "features.module.4.weight", "features.module.4.bias", "features.module.4.running_mean", "features.module.4.running_var", "features.module.7.weight", "features.module.7.bias", "features.module.8.weight", "features.module.8.bias", "features.module.8.running_mean", "features.module.8.running_var", "features.module.10.weight", "features.module.10.bias", "features.module.11.weight", "features.module.11.bias", "features.module.11.running_mean", "features.module.11.running_var", "features.module.14.weight", "features.module.14.bias", "features.module.15.weight", "features.module.15.bias", "features.module.15.running_mean", "features.module.15.running_var", "features.module.17.weight", "features.module.17.bias", "features.module.18.weight", "features.module.18.bias", "features.module.18.running_mean", "features.module.18.running_var", "features.module.20.weight", "features.module.20.bias", "features.module.21.weight", "features.module.21.bias", "features.module.21.running_mean", "features.module.21.running_var", "features.module.24.weight", "features.module.24.bias", "features.module.25.weight", "features.module.25.bias", "features.module.25.running_mean", "features.module.25.running_var", "features.module.27.weight", "features.module.27.bias", "features.module.28.weight", "features.module.28.bias", "features.module.28.running_mean", "features.module.28.running_var", "features.module.30.weight", "features.module.30.bias", "features.module.31.weight", "features.module.31.bias", "features.module.31.running_mean", "features.module.31.running_var", "features.module.34.weight", "features.module.34.bias", "features.module.35.weight", "features.module.35.bias", "features.module.35.running_mean", "features.module.35.running_var", "features.module.37.weight", "features.module.37.bias", "features.module.38.weight", "features.module.38.bias", "features.module.38.running_mean", "features.module.38.running_var", "features.module.40.weight", "features.module.40.bias", "features.module.41.weight", "features.module.41.bias", "features.module.41.running_mean", "features.module.41.running_var". 
`

**Comment by JonMuehlst** [comment]
It appears that the string '.module' is unexpected.
Renaming the keys fixes the issue:

`from collections import OrderedDict`
`state_dict = OrderedDict((k.replace('.module', ''), v) for k, v in checkpoint['state_dict'].items())`

`model.load_state_dict(state_dict)`
`

**Comment by JonMuehlst** [comment]
Just realized that util.load_model deals with this issue gracefully.
