### ISSUE TITLE
OOM for K=10^5

### ISSUE THREAD

**Issue by shlokk** [facebookresearch/deepcluster#38]
When I'm trying to run on K=10^5 clusters. 
I'm getting OOM issues.
the shape of data in the cluster
(1281167, 4096)
Traceback (most recent call last):
  File "main_resnet_18_sobel.py", line 392, in <module>
    main()
  File "main_resnet_18_sobel.py", line 198, in main
    clustering_loss = deepcluster.cluster(features, verbose=args.verbose)
  File "deepcluster/clustering.py", line 208, in cluster
    I, loss = run_kmeans(xb, self.k, verbose)
  File "deepcluster/clustering.py", line 168, in run_kmeans
    index = faiss.GpuIndexFlatL2(res, d, flat_config)
  File "lib/python3.7/site-packages/faiss/__init__.py", line 333, in replacement_init
    original_init(self, *args)
  File "lib/python3.7/site-packages/faiss/swigfaiss.py", line 5430, in __init__
    this = _swigfaiss.new_GpuIndexFlatL2(*args)
RuntimeError: Error in void faiss::gpu::allocMemorySpaceV(faiss::gpu::MemorySpace, void**, size_t) at gpu/utils/MemorySpace.cpp:27: Error: 'err == cudaSuccess' failed: failed to cudaMalloc 1610612736 bytes (error 2 out of memory)

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest.
Please refer to [Faiss](https://github.com/facebookresearch/faiss) for pure Faiss issues.
As a matter of fact, your matrix is of size ~21Gb (4*1281167*4096) which is unlikely to fit in GPU memory. Consider [reducing](https://github.com/facebookresearch/deepcluster/blob/726ce2d10a9878ddcc39a1c70f1a16cec3eb6f83/clustering.py#L88) the dim of the descriptors (I used 256d in my paper) before clustering them.
Hope that helps
