### ISSUE TITLE
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:23

### ISSUE THREAD

**Issue by onishimal99** [facebookresearch/deepcluster#77]
```
Traceback (most recent call last):
  File "eval_linear.py", line 325, in <module>
    main()
  File "eval_linear.py", line 140, in main
    train(train_loader, model, reglog, criterion, optimizer, epoch)
  File "eval_linear.py", line 251, in train
    prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
  File "eval_linear.py", line 213, in accuracy
    _, pred = output.topk(maxk, 1, True, 
```

RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:23

When I run `./eval_linear.sh`,this error was returned.

Does anyone have any ideas on this issue?

**Comment by DDxk369** [comment]
The same problem also happened to me. Have you solved it?

**Comment by KuntimaKiala** [comment]
For those who found the same problem as me, you have to reduce the maxk
